FROM tophfr/mailcatcher
#FROM ruby:2.2-alpine
#
## Install mailcatcher Server
#RUN apk add --no-cache \
#      g++ \
#      make \
#      sqlite \
#      sqlite-libs \
#      sqlite-dev
#
#RUN gem install mailcatcher -v 0.6.4 --no-ri --no-rdoc
#RUN apk del \
#      g++ \
#      make \
#      sqlite-libs
#
## SMTP Server
#EXPOSE 1025
## HTTP Server
#EXPOSE 1080
